// mcu_qsys_hps_0.v

// This file was auto-generated from altera_hps_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module mcu_qsys_hps_0 #(
		parameter F2S_Width = 0,
		parameter S2F_Width = 0
	) (
		output wire [66:0] h2f_loan_in,               // h2f_loan_io.in
		input  wire [66:0] h2f_loan_out,              //            .out
		input  wire [66:0] h2f_loan_oe,               //            .oe
		output wire        h2f_rst_n,                 //   h2f_reset.reset_n
		input  wire        uart0_cts,                 //       uart0.cts
		input  wire        uart0_dsr,                 //            .dsr
		input  wire        uart0_dcd,                 //            .dcd
		input  wire        uart0_ri,                  //            .ri
		output wire        uart0_dtr,                 //            .dtr
		output wire        uart0_rts,                 //            .rts
		output wire        uart0_out1_n,              //            .out1_n
		output wire        uart0_out2_n,              //            .out2_n
		input  wire        uart0_rxd,                 //            .rxd
		output wire        uart0_txd,                 //            .txd
		output wire [12:0] mem_a,                     //      memory.mem_a
		output wire [2:0]  mem_ba,                    //            .mem_ba
		output wire        mem_ck,                    //            .mem_ck
		output wire        mem_ck_n,                  //            .mem_ck_n
		output wire        mem_cke,                   //            .mem_cke
		output wire        mem_cs_n,                  //            .mem_cs_n
		output wire        mem_ras_n,                 //            .mem_ras_n
		output wire        mem_cas_n,                 //            .mem_cas_n
		output wire        mem_we_n,                  //            .mem_we_n
		output wire        mem_reset_n,               //            .mem_reset_n
		inout  wire [7:0]  mem_dq,                    //            .mem_dq
		inout  wire        mem_dqs,                   //            .mem_dqs
		inout  wire        mem_dqs_n,                 //            .mem_dqs_n
		output wire        mem_odt,                   //            .mem_odt
		output wire        mem_dm,                    //            .mem_dm
		input  wire        oct_rzqin,                 //            .oct_rzqin
		inout  wire        hps_io_gpio_inst_LOANIO49, //      hps_io.hps_io_gpio_inst_LOANIO49
		inout  wire        hps_io_gpio_inst_LOANIO50  //            .hps_io_gpio_inst_LOANIO50
	);

	wire   [8:0] fpga_interfaces_loanio_gpio_loanio2_oe; // fpga_interfaces:loanio_gpio_loanio2_oe -> hps_io:gpio_loanio_loanio2_oe
	wire   [8:0] fpga_interfaces_loanio_gpio_loanio2_o;  // fpga_interfaces:loanio_gpio_loanio2_o -> hps_io:gpio_loanio_loanio2_o
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio1_oe; // fpga_interfaces:loanio_gpio_loanio1_oe -> hps_io:gpio_loanio_loanio1_oe
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio1_o;  // fpga_interfaces:loanio_gpio_loanio1_o -> hps_io:gpio_loanio_loanio1_o
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio0_o;  // fpga_interfaces:loanio_gpio_loanio0_o -> hps_io:gpio_loanio_loanio0_o
	wire  [28:0] hps_io_gpio_loanio_loanio1_i;           // hps_io:gpio_loanio_loanio1_i -> fpga_interfaces:loanio_gpio_loanio1_i
	wire  [28:0] hps_io_gpio_loanio_loanio0_i;           // hps_io:gpio_loanio_loanio0_i -> fpga_interfaces:loanio_gpio_loanio0_i
	wire   [8:0] hps_io_gpio_loanio_loanio2_i;           // hps_io:gpio_loanio_loanio2_i -> fpga_interfaces:loanio_gpio_loanio2_i
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio0_oe; // fpga_interfaces:loanio_gpio_loanio0_oe -> hps_io:gpio_loanio_loanio0_oe

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (F2S_Width != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					f2s_width_check ( .error(1'b1) );
		end
		if (S2F_Width != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					s2f_width_check ( .error(1'b1) );
		end
	endgenerate

	mcu_qsys_hps_0_fpga_interfaces fpga_interfaces (
		.h2f_loan_in            (h2f_loan_in),                            // h2f_loan_io.in
		.h2f_loan_out           (h2f_loan_out),                           //            .out
		.h2f_loan_oe            (h2f_loan_oe),                            //            .oe
		.loanio_gpio_loanio0_i  (hps_io_gpio_loanio_loanio0_i),           // loanio_gpio.loanio0_i
		.loanio_gpio_loanio0_oe (fpga_interfaces_loanio_gpio_loanio0_oe), //            .loanio0_oe
		.loanio_gpio_loanio0_o  (fpga_interfaces_loanio_gpio_loanio0_o),  //            .loanio0_o
		.loanio_gpio_loanio1_i  (hps_io_gpio_loanio_loanio1_i),           //            .loanio1_i
		.loanio_gpio_loanio1_oe (fpga_interfaces_loanio_gpio_loanio1_oe), //            .loanio1_oe
		.loanio_gpio_loanio1_o  (fpga_interfaces_loanio_gpio_loanio1_o),  //            .loanio1_o
		.loanio_gpio_loanio2_i  (hps_io_gpio_loanio_loanio2_i),           //            .loanio2_i
		.loanio_gpio_loanio2_oe (fpga_interfaces_loanio_gpio_loanio2_oe), //            .loanio2_oe
		.loanio_gpio_loanio2_o  (fpga_interfaces_loanio_gpio_loanio2_o),  //            .loanio2_o
		.h2f_rst_n              (h2f_rst_n),                              //   h2f_reset.reset_n
		.uart0_cts              (uart0_cts),                              //       uart0.cts
		.uart0_dsr              (uart0_dsr),                              //            .dsr
		.uart0_dcd              (uart0_dcd),                              //            .dcd
		.uart0_ri               (uart0_ri),                               //            .ri
		.uart0_dtr              (uart0_dtr),                              //            .dtr
		.uart0_rts              (uart0_rts),                              //            .rts
		.uart0_out1_n           (uart0_out1_n),                           //            .out1_n
		.uart0_out2_n           (uart0_out2_n),                           //            .out2_n
		.uart0_rxd              (uart0_rxd),                              //            .rxd
		.uart0_txd              (uart0_txd)                               //            .txd
	);

	mcu_qsys_hps_0_hps_io hps_io (
		.gpio_loanio_loanio0_i     (hps_io_gpio_loanio_loanio0_i),           // gpio_loanio.loanio0_i
		.gpio_loanio_loanio0_oe    (fpga_interfaces_loanio_gpio_loanio0_oe), //            .loanio0_oe
		.gpio_loanio_loanio0_o     (fpga_interfaces_loanio_gpio_loanio0_o),  //            .loanio0_o
		.gpio_loanio_loanio1_i     (hps_io_gpio_loanio_loanio1_i),           //            .loanio1_i
		.gpio_loanio_loanio1_oe    (fpga_interfaces_loanio_gpio_loanio1_oe), //            .loanio1_oe
		.gpio_loanio_loanio1_o     (fpga_interfaces_loanio_gpio_loanio1_o),  //            .loanio1_o
		.gpio_loanio_loanio2_i     (hps_io_gpio_loanio_loanio2_i),           //            .loanio2_i
		.gpio_loanio_loanio2_oe    (fpga_interfaces_loanio_gpio_loanio2_oe), //            .loanio2_oe
		.gpio_loanio_loanio2_o     (fpga_interfaces_loanio_gpio_loanio2_o),  //            .loanio2_o
		.mem_a                     (mem_a),                                  //      memory.mem_a
		.mem_ba                    (mem_ba),                                 //            .mem_ba
		.mem_ck                    (mem_ck),                                 //            .mem_ck
		.mem_ck_n                  (mem_ck_n),                               //            .mem_ck_n
		.mem_cke                   (mem_cke),                                //            .mem_cke
		.mem_cs_n                  (mem_cs_n),                               //            .mem_cs_n
		.mem_ras_n                 (mem_ras_n),                              //            .mem_ras_n
		.mem_cas_n                 (mem_cas_n),                              //            .mem_cas_n
		.mem_we_n                  (mem_we_n),                               //            .mem_we_n
		.mem_reset_n               (mem_reset_n),                            //            .mem_reset_n
		.mem_dq                    (mem_dq),                                 //            .mem_dq
		.mem_dqs                   (mem_dqs),                                //            .mem_dqs
		.mem_dqs_n                 (mem_dqs_n),                              //            .mem_dqs_n
		.mem_odt                   (mem_odt),                                //            .mem_odt
		.mem_dm                    (mem_dm),                                 //            .mem_dm
		.oct_rzqin                 (oct_rzqin),                              //            .oct_rzqin
		.hps_io_gpio_inst_LOANIO49 (hps_io_gpio_inst_LOANIO49),              //      hps_io.hps_io_gpio_inst_LOANIO49
		.hps_io_gpio_inst_LOANIO50 (hps_io_gpio_inst_LOANIO50)               //            .hps_io_gpio_inst_LOANIO50
	);

endmodule
